### ISSUE TITLE
Can't deploy without purging build cache

### ISSUE THREAD

**Issue by dentarg** [heroku/heroku-buildpack-ruby#1294]
Reported to Heroku support as ticket 1092887

Since today we are not able to able to deploy our app without first clearing the build cache (https://devcenter.heroku.com/articles/slug-compiler#build-cache)

This was our setup when the day started:

    === Buildpack URLs
    1. https://github.com/heroku/heroku-buildpack-github-netrc.git
    2. https://github.com/heroku/heroku-buildpack-nodejs.git
    3. https://github.com/heroku/heroku-buildpack-ruby.git

You can see that we ran using the master branch of the heroku/ruby buildpack,
meaning we used all the latest changes: https://github.com/heroku/heroku-buildpack-ruby/commit/b7c8180bd9add46e179346f691ff1e339b87357c

It failed like this

    remote: -----> Installing dependencies using bundler 2.2.33
    remote:        Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
    remote:        [248, #<Thread:0x00007f549f6e3c78 run>, #<NameError: uninitialized constant Gem::Source
    remote:
    remote:              (defined?(@source) && @source) || Gem::Source::Installed.new
    remote:                                                   ^^^^^^^^

Which has been reported in https://github.com/heroku/heroku-buildpack-ruby/issues/1280 / https://github.com/rubygems/rubygems/issues/5351

We then tried many different things to get deploys working reliably again

- changing ruby version (`.ruby-version`) from 3.1.1 to 3.1.0
- updating bundler in `Gemfile.lock` from 2.3.7 to 2.3.10
- deploying after doing `heroku labs:enable build-in-app-dir` for the app
- using v237 of heroku/ruby buildpack
- using the latest released version of heroku/ruby buildpack
- switching stack to heroku-18 (works the first time because the build cache is purged)
- switching stack back to heroku-20 (works the first time because the build cache is purged)
- switching stack back to heroku-18 (works the first time because the build cache is purged)

We changed the buildpack setup to be (and did `heroku labs:disable build-in-app-dir`)

    === Buildpack URLs
    1. https://github.com/heroku/heroku-buildpack-github-netrc.git
    2. heroku/nodejs
    3. heroku/ruby

and updated `.ruby-version` to contain `3.1.1` again

Deploys still fail with the `uninitialized constant Gem::Source` error (https://github.com/rubygems/rubygems/issues/5351) unless we purge the build cache before the deploy.

Yes, our `Gemfile` uses gems hosted in private git repos on GitHub.

How can we get out of this situation?

**Comment by dentarg** [comment]
Yeah we are not alone in this: https://github.com/heroku/heroku-buildpack-ruby/issues/1273#issuecomment-1085735905

**Comment by bmulholland** [comment]
I've got ticket 1092855 open about the exact same thing.

I'm pretty unimpressed with EST-only support hours for essential infrastructure.

**Comment by krsyoung** [comment]
Huge thanks for sharing this! I was down a completely wrong rathole. 

For anybody else looking for a stopgap, this fixed the issue blocking our dokku 0.27.0 deployments today (thanks @dentarg).

```
dokku repo:purge-cache <app>
```

After running that we were able to push successfully.

**Comment by dentarg** [comment]
Okay, looks like we can deploy if we purge the build cache and downgrade to Ruby 3.1.0

**Comment by dentarg** [comment]
I guess that's because Ruby 3.1.0 doesn't have Bundler 2.3.7. That's unfortunate, as there's a decent list of bug fixes for Ruby 3.1.1 https://www.ruby-lang.org/en/news/2022/02/18/ruby-3-1-1-released/

Ping @schneems

**Comment by moveson** [comment]
> I guess that's because Ruby 3.1.0 doesn't have Bundler 2.3.7. That's unfortunate, as there's a decent list of bug fixes for Ruby 3.1.1 https://www.ruby-lang.org/en/news/2022/02/18/ruby-3-1-1-released/
> 
> Ping @schneems

You can bundle with an older version of bundler. Just install an older version (Heroku uses 2.2.33) and then bundle specifying that version:
```
gem install bundler:2.2.33
bundle _2.2.33_
```

**Comment by schinery** [comment]
> Yeah we are not alone in this: [#1273 (comment)](https://github.com/heroku/heroku-buildpack-ruby/issues/1273#issuecomment-1085735905)

Am also in this mire…

What I don’t get is that my Ruby 3.1.1 and Bundler 2.3.7 apps deployed fine up until yesterday afternoon. Deployed one app in the morning then realised something needed tweaking and could no longer deploy, although @bmulholland [comment about clearing the build cache](https://github.com/heroku/heroku-buildpack-ruby/issues/1273#issuecomment-1085683462) did the trick for a single deploy before reverting back to not deploying.

Downgrading Ruby and/or Bundler probably isn’t going to be an option so am hoping the Bundler upgrade to 2.3.9 (think that was the version) or another fix is found 🙏🏻

**Comment by dentarg** [comment]
@schinery I suspect some combination of gems trigger the bug in Bundler 2.3.7. I did notice that the last successful deploy in two different apps how ours updated Gemfile.lock before hitting this roadblock. Haven't had time to investigate that further though.

**Comment by caseyprovost** [comment]
Experiencing this issue as well, started seeing it yesterday April 2nd (didn't deploy between March 30 - April 1st)

**Comment by schneems** [comment]
The most curious part of this for me is the timing. I got a flurry of tickets about this and I"m looking into it. However, I can't figure out why it was working before.

We've not changed anything on our end on Friday. We did merge some stuff 7 days ago but that doesn't coincide with this starting to happen. https://github.com/heroku/heroku-buildpack-ruby/commits/main. Also @dentarg mentions that using the older version of the buildpack didn't fix the issue.

> I'm pretty unimpressed with EST-only support hours for essential infrastructure.

I'm aware of this limitation. As a result, I don't push changes in the evening or on Fridays (basically unless I can be in front of my computer for the next several hours). I would love to provide 24/7 support, but there's only one of me (currently). We do have many tier 1 supporters, but only ~one buildpack owner per language which would be required for such an in-depth investigation.

Under normal circumstances the ability to rollback your own deploys `heroku rollback` and to pin to an older release of the buildpack https://devcenter.heroku.com/articles/bundler-version#using-an-older-version-of-bundler are enough of an escape valve to buy a day or two. 

In this case either something external triggered this event that Heroku can't control or many people started doing something different at about the same time. I'm glad that yall found one another and were able to come up with a workaround in the short term. Even though I'm paid to work on this OSS I can't do it all and rely on "many eyes" for help etc. Sorry you've had to wait.

> You shouldn't need to downgrade your Ruby version. You can bundle with an older version of bundler. Just install an older version (Heroku uses 2.2.33) and then bundle specifying that version:

We (heroku) don't invoke the command this way, we use `bundle install` which goes through the rubygems lookup process which picks the latest version that satisfies. When Ruby 3.1.1 the Bundler version is later than the one we've put on the platform for you. That's an interesting idea. In the CNB re-write I was going the other direction with the ability to use any arbitrary bundler version that you've got in your Gemfile.lock. That's a tangent though.

I'm going to keep debugging this and looking into the root cause. Also since this seems to be bundler/rubygems related one lever I've got is to be able to release a newer bundler version. I wanted to do it before and had to roll back. I'm hoping those issues have been ironed out. I'll go ahead and stage that on a branch and ask anyone who has this issue to try it out (and comment out your temp `bin/bundle` fix). 

In the mean time if you've got any other theories about what changed or why this suddenly started happening I'm all ears.

**Comment by bmulholland** [comment]
Another clue is that it seems fixed for us today…

The only thing I can think that was different for us on Friday is that the pg gem did an April fools that wrote to stdout during bundle install, and that only happened on April 1. I did see someone complain about that affecting their infrastructure: https://github.com/ged/ruby-pg/issues/449

**Comment by schneems** [comment]
>  pg gem did an April fools that wrote to stdout during bundle install, and that only happened on April 1.

Wow, that's surprising. I'll want to figure out the failure mode for sure because it sound's like there's something that might be fragile in our build process that we could fix.

> Experiencing this issue as well, started seeing it yesterday April 2nd (didn't deploy between March 30 - April 1st)

That comment makes me think it might be something else, but also maybe it's a timezone issue with the "joke". 

If anyone is still experiencing this please let me know. Internal ticket numbers are appreciated too on this thread. 

I've published a branch that uses the latest bundler version 2.3.10. You can replace your heroku/ruby buildpack with this https://github.com/heroku/heroku-buildpack-ruby#schneems/bundler-2-3-10 to try it on your app using the heroku buildpacks command. Give that a shot and let me know if it fixes the problem (without the bin/bundle workaround). Here's the PR https://github.com/heroku/heroku-buildpack-ruby/pull/1296

**Comment by schneems** [comment]
I see failing builds as recently as a few hours ago.

**Comment by navinpeiris** [comment]
Still seeing this as well. Deployments failing currently unless we purge the cache first.

**Comment by wrburgess** [comment]
Same behavior for my app

**Comment by teoljungberg** [comment]
I can conform that replacing the buildpack with https://github.com/heroku/heroku-buildpack-ruby/pull/1296 worked for us and we can deploy again.

**Comment by schneems** [comment]
> Even after purging the cache on Heroku, it still does not deploy.

That sounds like a different ticket. I recommend opening a Heroku support request.


> I can conform that replacing the buildpack with https://github.com/heroku/heroku-buildpack-ruby/pull/1296 worked for us and we can deploy again.

Awesome, thanks for the verification. I've looked into this more and what seems to be happening is that the code that calls Gem::Source is found only in Bundler when bundler has found a file on disk. I.e. on the second deploy when the cache is populated. 

While it seems like this problem suddenly manifested itself, my current theory is that it affects all Ruby 3.1.1 apps, but only on the second deploy. (Though maybe with some other set of complicating factors as 3.1.1 was released about 2 months ago and for sure people have deployed twice with it). WIth that theory I decided I could test it by trying v236 deploy of the buildpack `https://github.com/heroku/heroku-buildpack-ruby#v236` it still had the same behavior.

With that theory blown, I hunted down logs on an app to see when it started failing. I saw Ruby 3.1.1 use for many deploys, and I saw lots of those deploys using the cache. However this stood out from the deploy right before it started failing:

```
```

**Comment by bmulholland** [comment]
FYI we've been on Ruby 3.1.1 since March 11 and have had many successful deploys between then and Friday.

**Comment by tomdracz** [comment]
Commenting to subscribe - just tried app update to 3.1.1 and it's similar to what's described above. First deploy went smoothly, second one started failing with `uninitialized constant Gem::Source`. Adding `require "rubygems/source"` to `bin/bundle` allowed subsequent deploys to work. Haven't tried the other buildpack but will try that tomorrow

**Comment by schneems** [comment]
Got some race conditions in that comment submission. I just updated my comment with a LOT of detail, check it out. I'll be heads down deploying my patch for a bit. I'll let you all know when it's done.

**Comment by tomdracz** [comment]
Thanks @schneems For what it's worth my failed upgrade did involve installing `net-protocol` (0.1.3) when I had to add `net-smtp`, `net-imap` and `net-pop` as `mail` gem depends on those. No idea if this is related in any way but 🤷 Will try out a patch when it's deployed and report back!

**Comment by schneems** [comment]
This change is released https://devcenter.heroku.com/changelog-items/2409 please try to deploy using the `heroku/ruby` buildpack now.

**Comment by tomdracz** [comment]
@schneems Successful deploy here with the `heroku/ruby` buildpack and `require "rubygems/source"` removed. Can see it's using bundler 2.3.10 in the output.

All good on this end. Thanks a lot!

**Comment by wrburgess** [comment]
Can confirm the fix is working for me

**Comment by schneems** [comment]
> Can confirm the fix is working for me

Awesome. Thanks for the feedback. I'm going to close this issue now. If someone has a different failure message or mode please open a ticket about it so I have access to logs. If you've got the same failure mode even with this update, also let me know (I want to try to separate new issues that might be from this change versus debugging this specific issue).

Thanks again to everyone who posted. Sorry that this all broke. I'm glad we were able to get up and running.

**Comment by Henryvw** [comment]
Thanks for your help and work on it @schneems. Cheers!

**Comment by caseyprovost** [comment]
Confirmed all is well now, thanks scheems!!!!
